### ISSUE TITLE
TypeError: feed is null feeds.js:598:17

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/remoteaccess#23]
![image](https://user-images.githubusercontent.com/503186/50111445-b59c8700-0234-11e9-8dde-84c5ccbbc67f.png)

Feed/list works but graph will not load on home system.
Works fine with office test...

**Comment by emrysr** [comment]
thanks @TrystanLea for helping me debug this issue...

This error is raised when the local installation of EmonCMS does not handle the `feed/data` endpoint with the parameter `ids="1,2,3"` and not `id=1`.

The api returns "Feed not found" as not single id is passed. check for this returned value and notify the user they need to update their emoncms install.

**Comment by emrysr** [comment]
feed/data multiple ids now in master thanks @TrystanLea 
https://github.com/emoncms/emoncms/commit/5f995ab667690123e3de3c2ef80b8072048fa19c

**Comment by emrysr** [comment]
@TrystanLea - I think this can be closed now
